#!/bin/bash

light=$(ps -x | grep redshift | head -n 1 | awk '{print $6}' | cut -d "." -f2)

if [[ $light =~ ^[+-]?[0-9]+$ ]]; then
	echo "Input is an integer."
else
light=$(ps -x | grep redshift | head -n 1 | awk '{print $6}' | cut -d "." -f2)

	if
fi
echo $light