#!/bin/bash

MONITORRT=HDMI-0
MONITORLT=DVI-D-0

function usage()
	{
		echo -e "Usage: $0 [OPTION]"
		echo -e ""
		echo -e "DSM - dual screen manager is based on 'xrandr' engine used to handle X11 server."
		echo -e "To run this script into your configuration you have to exec, at the first run, the '-ck' option and substitute the output in the variables into the script file"
		echo -e ""
		echo -e ""
		echo -e "It requires one of the following OPTIONS\n"
		echo -e " -onr\t turn on the right monitor"
		echo -e " -onl\t turn on the left monitor"
		echo -e " -offr\t shutdown the right monitor"
		echo -e " -offl\t shutdown the left monitor"
		echo -e " -prt\t put the left monitor in portrait mode"
		echo -e " -norm\t put the left monitor in landscape mode"
		echo -e " -ck\t check the monitors configuration"
		echo -e " -h\t display this help"
		echo -e "\n"
 	}

if [ $# -eq 1 ]; then
		if [ -n "$1" ]; then
			case "$1" in
				-onr) xrandr --output $MONITORRT --mode 1920x1080 --right-of $MONITORLT
				;;
				-onl) xrandr --output $MONITORLT --mode 1920x1080 --left-of $MONITORRT
				;;
				-offr) xrandr --output $MONITORRT --off
				;;
				-offl) xrandr --output $MONITORLT --off
				;;
				-prt) xrandr --output $MONITORLT --rotate right
				;;
				-norm) xrandr --output $MONITORLT --rotate normal
				;;
				-ck) xrandr | grep -w connected | cut -d ' ' -f1
				;;
				-h) usage
				;;
				*) 	echo -e "Option $1 not recognized"
						echo "Try '$0 -h' for more information."
				;;
			esac	
		fi
else
  echo "missing arguments" 
  echo "Try '$0 -h' for more information."
fi
